apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform
---
apiVersion: v1
kind: Pod
metadata:
  name: terraform
spec:
  serviceAccountName: terraform
  containers:
  - name: centos
    image: centos:7
    command:
    - sleep
    - "10000000"

