- name: Add users
  hosts: localhost
  vars_files:
    - user-list.yml
  tasks:
    - name: Generate random password
      set_fact:
        random_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
      loop: "{{USERS}}"
    - name: Print Password
      debug:
        msg: "{{random_password}}"
        